services:
  myntra-prs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    container_name: myntra-prs-backend
    restart: unless-stopped
