name: Deploy Backend to AWS Lambda via ECR

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

env:
  AWS_REGION: ap-south-1
  ECR_REPO: myntra-prs-backend

jobs:
  terraform_setup:
    name: 🛠️ Terraform - ECR & IAM Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply - Create ECR only
        run: terraform apply -target=aws_ecr_repository.backend -auto-approve
        working-directory: terraform

  docker_push:
    name: 🐳 Build & Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: terraform_setup

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ env.ECR_REPO }} backend/
          docker tag ${{ env.ECR_REPO }}:latest ${{ steps.login.outputs.registry }}/${{ env.ECR_REPO }}:latest
          docker push ${{ steps.login.outputs.registry }}/${{ env.ECR_REPO }}:latest

  terraform_lambda:
    name: 🚀 Deploy Lambda with Image
    runs-on: ubuntu-latest
    needs: docker_push

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply - Create Lambda with Image
        run: terraform apply -auto-approve
        working-directory: terraform
