name: Deploy Backend to AWS Lambda via ECR

on:
  workflow_dispatch:
  # Uncomment below to auto-deploy on push to master
  # push:
  #   branches:
  #     - master

env:
  AWS_REGION: ap-south-1
  ECR_REPO: myntra-prs-backend

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan & Apply
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
        working-directory: terraform

      - name: Login to ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ env.ECR_REPO }} backend/
          docker tag ${{ env.ECR_REPO }}:latest ${{ steps.login.outputs.registry }}/${{ env.ECR_REPO }}:latest
          docker push ${{ steps.login.outputs.registry }}/${{ env.ECR_REPO }}:latest
