name: Backend Destroy

on:
  workflow_dispatch:
  # Uncomment below to auto-deploy on push to master
  # push:
  #   branches:
  #     - master

env:
  AWS_REGION: ap-south-1
  TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
  TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
  TF_VAR_frontend_url: ${{ secrets.FRONTEND_URL }}

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
